background #181818
foreground #e0e0e0

cursor #c8945a
cursor_text_color #1c1814
url_color #c8945a

# color surface 2
# color fg
selection_background #423930
selection_foreground #e8ddd0

# color bg
# color surface 2
color0 #1c1814
color8 #423930

# red -> errors,deletion
color1 #8c5a50
color9 #a8708a

# green -> success,additions
color2  #6a7a54
color10 #849668

# yellow -> warnings
# color dim
# color accent	
color3  #c4b8ac
color11 #c8945a 

# blue -> info
color4  #4e5860
color12 #669080

# magenta -> special
color5  #7a5a60
color13 #987078

# cyan -> strings,links
# color border 
# color muted 
color6  #584e44
color14 #7a6e62

# white -> regular text
# color dim
# color fg
color7  #c4b8ac
color15 #e8ddd0
