# border color
client.focused #8a5e2e #8a5e2e #ffffff #8a5e2e
client.unfocused #1a1a1a #1a1a1a #888888 #1a1a1a
client.focused_inactive #1a1a1a #1a1a1a #888888 #1a1a1a

# window title
default_border pixel 2
titlebar_padding 1
#font pango:monospace 0.001 # removes title
