# main modifier
set $mod Mod4

# system binds
bindsym $mod+c kill
bindsym $mod+Shift+r reload
bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'

# movement
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# window movement
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right


# workspace movement
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

#resize mode
mode "resize" {
    bindsym h resize shrink width 10 px
    bindsym j resize grow height 10 px
    bindsym k resize shrink height 10 px
    bindsym l resize grow width 10 px

    bindsym Escape mode "default"
    bindsym $mod+r mode "default"
}
bindsym $mod+r mode "resize"

# sendtoworkspace mode
mode "sendtoworkspace" {
	bindsym 1 move container to workspace 1; mode "default"
	bindsym 2 move container to workspace 2; mode "default"
	bindsym 3 move container to workspace 3; mode "default"
	bindsym 4 move container to workspace 4; mode "default"
	bindsym 5 move container to workspace 5; mode "default"
	bindsym 6 move container to workspace 6; mode "default"
	bindsym 7 move container to workspace 7; mode "default"
	bindsym 8 move container to workspace 8; mode "default"
	bindsym 9 move container to workspace 9; mode "default"
	bindsym 0 move container to workspace 10; mode "default"

	bindsym Escape mode "default"
    bindsym $mod+s mode "default"
}
bindsym $mod+s mode "sendtoworkspace"

# launcher mode
mode "launcher" {
	bindsym t exec kitty; mode "default"
	bindsym b exec qutebrowser; mode "default"
	bindsym d exec webcord; mode "default"
	bindsym s exec moonlight; mode "default"
	bindsym m exec kitty -e jellyfin-tui; mode "default"
	bindsym e exec emacsclient -c; mode "default"

	bindsym Escape mode "default"
    bindsym $mod+a mode "default"
}
bindsym $mod+a mode "launcher" 

# utility mode
mode "utility" {
	bindsym a exec kitty -e wiremix; mode "default"
	bindsym b exec kitty -e bluetui; mode "default"
	bindsym n exec kitty -e impala; mode "default"

	bindsym Escape mode "default"
    bindsym $mod+u mode "default"
}
bindsym $mod+u mode "utility"

# layouts

bindsym $mod+b splith
bindsym $mod+v splitv

bindsym $mod+q layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

bindsym $mod+f fullscreen

bindsym $mod+Shift+f floating toggle

# scratchpad
bindsym $mod+z move scratchpad
bindsym $mod+x scratchpad show
