[ids]
*

[main]
space = overload(layer, space)

a = overloadi(a, overload2(meta, a, 200), 150)
s = overloadi(s, overload2(control, s, 200), 150)
d = overloadi(d, overload2(alt, d, 200), 150)
f = overloadi(f, overload2(shift, f, 200), 150)

n = overloadi(n, overload2(shift, n, 200), 150)
m = overloadi(m, overload2(control, m, 200), 150)
; = overloadi(;, overload2(meta, ;, 200), 150)
i = overloadi(i, overload2(alt, i, 200), 150)

capslock = esc

[layer]
a = 1
s = 2
d = 3
f = 4
g = 5
h = 6
j = 7
k = 8
l = 9
; = 0
' = -
\ = =

q = !
w = @
e = #
r = $
t = %
y = ^
u = &
i = *
o = (
p = )
[ = _
] = +

c = left
v = down
m = up
, = right


n = backspace
b = enter
